server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: nikucha666
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
